In [1]:
import numpy as np

In [2]:
# ЗАДАНИЕ 1 СОЗДАНИЕ ARRAY

n = int(input("Число элементов массива: "))
n_array = np.arange(n-1, -1, -1)
print(n_array)


Число элементов массива: 3
[2 1 0]


In [3]:
# ЗАДАНИЕ 2 СОЗДАНИЕ ДИАГОНАЛЬНОЙ МАТРИЦЫ

n = int(input("Начальный элемент для диагональной матрицы: "))
diag_matx = np.diag(np.arange(n, -1, -1))
print(diag_matx)
sum(sum(diag_matx))


Начальный элемент для диагональной матрицы: 3
[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]]


6

In [4]:
# ЗАДАНИЕ 3 РЕШЕНИЕ УРАВНЕНИЙ
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

coef = np.array([[4,2,1],[1,3,0],[0,5,4]])
values = np.array([4,12,-3])
from numpy import linalg
linalg.solve(coef,values)

array([ 0.46666667,  3.84444444, -5.55555556])

In [5]:
# ЗАДАНИЕ 4 ВЕКТОРЫ

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 5, 4, 8, 1, 4]
        
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

min_cos = 1
the_most_similar = 0

for user in users_stats:
    cosin = np.dot(next_user_stats, user)/(np.linalg.norm( user )* np.linalg.norm( next_user_stats ))
    if cosin < min_cos:
        min_cos = cosin
        the_most_similar = user
print(f'Минимальное расстояние - {min_cos} \nМаксимально похожий пользователь - {the_most_similar} ')

Минимальное расстояние - 0.0 
Максимально похожий пользователь - [0 0 0 0 0 5] 
